config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord

    searchkick text_middle: %i[title body]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    def index
        @results = search_for_posts

        respond_to do |format|
            format.turbo_stream do
                render turbo_stream: turbo_stream.update("posts", partial: "posts/posts", locals: {posts: @results}) 
            end
        end
    end
    
    def suggestions
        @results = search_for_posts

        respond_to do |format|
            format.turbo_stream do
                render turbo_stream: turbo_stream.update("suggestions", partial: "search/suggestions", locals: {results: @results}) 
            end
        end
    end

    private

    def search_for_posts
        if params[:query].blank?
            Post.all
        else
            Post.search(params[:query], fields: %i[title body], operator: "or", match: :text_middle)
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
  <div class="p-4 border border-gray-300 rounded-1g"> 
    <h2> <%= post.title%> </h2>
    <p> <%= post.body %> </p>
    <p>
      <%= link_to "Show this post", post, class: "text-blue-500" %>
    </p>
  </div>
<% end %>

<%# <%= render post %> 

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-4xl text-center mt-5 mb-4">Posts</h1>

<div class="flex justify-center"> 
  <%= render partial: "search/form", locals: { results: [] } %>
</div>

<div id="posts" class="mt-4 mx-10">
  <%= render "posts/posts", posts: @posts %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/search/_form.html.erb
<%= form_with(url: search_path, method: :post, class: "w-60", data: { 
    controller: "search",
    action: "keyup->search#suggestions",
    suggestions_url: search_suggestions_path,
 }) do |form| %>

    <div class="relative">

        <%= form.text_field :query, data: {
            search_target: "input",
            action: "blur->search#hideSuggestions",
        
        },
        class: "w-full p-2 border border-gray-300 rounded-lg focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200",
        placeholder: "Search...", autocomplete: "off"
        %>
        <div class="absolute inset-y-0 right-0 flex items-center">
            <%= form.submit "Search", class:"p-2 text-white bg-indigo-500 rounded-lg hover:big-indigo-600 focus:outline-none focus:bg-indigo-600" %> 
        </div>
        <div id="suggestions" class="absolute w-full mt-2 bg-white rounded-lg shadow-lg" data-search-targer="suggestions" data-action="mousedown->childClicked">
            <%= render partial: "search/suggestions", locals: { results: results } %>
        </div>
    </div>

 <% end %>

app/views/search/_suggestions.html.erb
<% if results.any? %>
    <div class="absolute w-full overflow-y-auto max-h-60 bg-white rounded-lg shadow-lg">
        <% results.each do |post| %>
            <div class="p-2 border-b border-gray-300 hover:bg-gray-100">
                <%= link_to post.title, post, class: "text-blue-500" %>
            </div>
        <% end %>
    </div>
<% end %>